QUEST_STATE_HIDDEN = 0
QUEST_STATE_INACTIVE = 1
QUEST_STATE_ACTIVE = 2
QUEST_STATE_COMPLETE = 3

QUEST_PROGRESS_0 = 0
QUEST_PROGRESS_50 = 1
QUEST_PROGRESS_80 = 2
QUEST_PROGRESS_100 = 3
#Actually, anything >1 will mark it as 80%. 3 is an arbitrary flag to mark the quest as Complete and set the progress 0

QUEST_REWARD_ITEM = 1
QUEST_REWARD_SHIP = 11


DOCK_TYPE_CRAFT = 1
DOCK_TYPE_REPAIR = 2

ITEM_TYPE_USABLE = 1
ITEM_TYPE_EQUIPMENT = 2
ITEM_TYPE_FURNITURE = 3

NAME_BUCKET = "高速修復材"
NAME_FLAME = "高速建造材"
NAME_MATERIAL = "開発資材"
NAME_SCREW = "改修資材"