"""empty message

Revision ID: 109c6ebf6cf
Revises: b5e404d415
Create Date: 2015-05-04 21:03:24.752126

"""

# revision identifiers, used by Alembic.
revision = '109c6ebf6cf'
down_revision = 'b5e404d415'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ship', sa.Column('torpedo_base', sa.Integer(), nullable=True))
    op.add_column('ship', sa.Column('torpedo_max', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ship', 'torpedo_max')
    op.drop_column('ship', 'torpedo_base')
    ### end Alembic commands ###
