"""Added API token to Admiral

Revision ID: 18a06a1308ae
Revises: f4ac668212c
Create Date: 2014-08-02 13:14:22.859765

"""

# revision identifiers, used by Alembic.
revision = '18a06a1308ae'
down_revision = 'f4ac668212c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admiral', sa.Column('api_token', sa.String(length=40), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admiral', 'api_token')
    ### end Alembic commands ###
