"""Add item table to db.

Revision ID: 18aee440c23
Revises: e9e831ffd0
Create Date: 2015-07-22 22:00:36.875607

"""

# revision identifiers, used by Alembic.
revision = '18aee440c23'
down_revision = 'e9e831ffd0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admiral_ship_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('usable', sa.Boolean(), nullable=True),
    sa.Column('increase_fp', sa.Boolean(), nullable=True),
    sa.Column('increase_aa', sa.Boolean(), nullable=True),
    sa.Column('increase_tp', sa.Boolean(), nullable=True),
    sa.Column('increase_ar', sa.Boolean(), nullable=True),
    sa.Column('increase_amount', sa.Integer(), nullable=False),
    sa.Column('rarity', sa.Integer(), nullable=False),
    sa.Column('sortno', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admiral_ship_id'], ['admiral_ship.id'], ),
    sa.PrimaryKeyConstraint('id', 'name')
    )
    op.add_column('ship', sa.Column('itemslots', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ship', 'itemslots')
    op.drop_table('item')
    ### end Alembic commands ###
