"""Add resources array to admiral data

Revision ID: 18b4843fcca
Revises: 109c6ebf6cf
Create Date: 2015-05-04 21:07:14.119536

"""

# revision identifiers, used by Alembic.
revision = '18b4843fcca'
down_revision = '109c6ebf6cf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admiral', sa.Column('resources', sa.String(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admiral', 'resources')
    ### end Alembic commands ###
