"""I didn't forget that One-to-Many exist.

Revision ID: 1ba40f8eb27
Revises: 91f3003b98
Create Date: 2015-05-05 14:38:32.707582

"""

# revision identifiers, used by Alembic.
revision = '1ba40f8eb27'
down_revision = '91f3003b98'


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
