"""Initial remodel migration.

Revision ID: 1f4f8dd0a86
Revises: None
Create Date: 2015-10-24 09:03:13.460816

"""

# revision identifiers, used by Alembic.
revision = '1f4f8dd0a86'
down_revision = None

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('furniture', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=True), sa.Column('number', sa.Integer(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True), sa.Column('type_', sa.Integer(), nullable=True),
        sa.Column('rarity', sa.Text(), nullable=True), sa.Column('season', sa.Integer(), nullable=True),
        sa.Column('price', sa.Integer(), nullable=True), sa.Column('sale_flag', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id'))
    op.create_table('resources', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('fuel', sa.Integer(), nullable=True), sa.Column('ammo', sa.Integer(), nullable=True),
        sa.Column('steel', sa.Integer(), nullable=True), sa.Column('baux', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id'))
    op.create_table('role', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=80), nullable=False), sa.Column('description', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'), sa.UniqueConstraint('name'))
    op.create_table('stats', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('luck', sa.Integer(), nullable=True), sa.Column('firepower', sa.Integer(), nullable=True),
        sa.Column('armour', sa.Integer(), nullable=True), sa.Column('torpedo', sa.Integer(), nullable=True),
        sa.Column('antiair', sa.Integer(), nullable=True), sa.Column('antisub', sa.Integer(), nullable=True),
        sa.Column('evasion', sa.Integer(), nullable=True), sa.Column('los', sa.Integer(), nullable=True),
        sa.Column('speed', sa.Integer(), nullable=True), sa.Column('dive_bomber', sa.Integer(), nullable=True),
        sa.Column('accuracy', sa.Integer(), nullable=True), sa.Column('range_', sa.Integer(), nullable=True),
        sa.Column('hp', sa.Integer(), nullable=True), sa.Column('ammo', sa.Integer(), nullable=True),
        sa.Column('fuel', sa.Integer(), nullable=True), sa.PrimaryKeyConstraint('id'))
    op.create_table('usable', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('api_id', sa.Integer(), nullable=True), sa.Column('name', sa.String(length=100), nullable=True),
        sa.Column('description', sa.String(), nullable=True), sa.Column('description2', sa.String(), nullable=True),
        sa.Column('category', sa.Integer(), nullable=True), sa.Column('type_', sa.Integer(), nullable=True),
        sa.Column('price', sa.Integer(), nullable=True), sa.PrimaryKeyConstraint('id'))
    op.create_table('user', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('active', sa.Boolean(), nullable=True), sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('password', sa.String(length=255), nullable=False),
        sa.Column('confirmed_at', sa.DateTime(), nullable=True),
        sa.Column('nickname', sa.String(length=255), nullable=False),
        sa.Column('api_token', sa.String(length=40), nullable=True), sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('api_token'), sa.UniqueConstraint('email'), sa.UniqueConstraint('nickname'))
    op.create_table('admiral', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=True), sa.Column('level', sa.Integer(), nullable=True),
        sa.Column('experience', sa.Integer(), nullable=True), sa.Column('rank', sa.Integer(), nullable=True),
        sa.Column('furniture_coins', sa.Integer(), nullable=True),
        sa.Column('max_kanmusu', sa.Integer(), nullable=True), sa.Column('max_equipment', sa.Integer(), nullable=True),
        sa.Column('max_furniture', sa.Integer(), nullable=True), sa.Column('sortie_total', sa.Integer(), nullable=True),
        sa.Column('sortie_successes', sa.Integer(), nullable=True),
        sa.Column('expedition_total', sa.Integer(), nullable=True),
        sa.Column('expedition_successes', sa.Integer(), nullable=True),
        sa.Column('pvp_total', sa.Integer(), nullable=True), sa.Column('pvp_successes', sa.Integer(), nullable=True),
        sa.Column('tutorial_progress', sa.Integer(), nullable=True),
        sa.Column('last_action', sa.DateTime(), nullable=True), sa.Column('last_login', sa.DateTime(), nullable=True),
        sa.Column('resources_id', sa.Integer(), nullable=True), sa.Column('user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['resources_id'], ['resources.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ), sa.PrimaryKeyConstraint('id'))
    op.create_table('equipment', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('sortno', sa.Integer(), nullable=True), sa.Column('api_id', sa.Integer(), nullable=True),
        sa.Column('name', sa.String(), nullable=True), sa.Column('info', sa.String(), nullable=True),
        sa.Column('rarity', sa.String(), nullable=True), sa.Column('types', sa.String(), nullable=True),
        sa.Column('resources_id', sa.Integer(), nullable=True), sa.Column('stats_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['resources_id'], ['resources.id'], ),
        sa.ForeignKeyConstraint(['stats_id'], ['stats.id'], ), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_equipment_resources_id'), 'equipment', ['resources_id'], unique=False)
    op.create_index(op.f('ix_equipment_stats_id'), 'equipment', ['stats_id'], unique=False)
    op.create_table('quest', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('no', sa.Integer(), nullable=True), sa.Column('category', sa.Integer(), nullable=True),
        sa.Column('type_', sa.Integer(), nullable=True), sa.Column('title', sa.String(length=255), nullable=True),
        sa.Column('detail', sa.Text(), nullable=True), sa.Column('bonus_flag', sa.Integer(), nullable=True),
        sa.Column('invalid_flag', sa.Integer(), nullable=True), sa.Column('code', sa.String(length=3), nullable=True),
        sa.Column('resources_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['resources_id'], ['resources.id'], ), sa.PrimaryKeyConstraint('id'))
    op.create_table('remodel', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('level', sa.Integer(), nullable=True), sa.Column('remodel_api_id', sa.Integer(), nullable=True),
        sa.Column('id_resources', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['id_resources'], ['resources.id'], ), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_remodel_id_resources'), 'remodel', ['id_resources'], unique=False)
    op.create_table('role__user', sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('role_id', sa.Integer(), nullable=True), sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ))
    op.create_table('admiral_equipment', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('level', sa.Integer(), nullable=True), sa.Column('locked', sa.Integer(), nullable=True),
        sa.Column('admiral_id', sa.Integer(), nullable=True), sa.Column('equipment_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['admiral_id'], ['admiral.id'], ),
        sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ), sa.PrimaryKeyConstraint('id'))
    op.create_table('admiral_furniture', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('active', sa.Boolean(), nullable=True), sa.Column('admiral_id', sa.Integer(), nullable=True),
        sa.Column('furniture_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['admiral_id'], ['admiral.id'], ),
        sa.ForeignKeyConstraint(['furniture_id'], ['furniture.id'], ), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_admiral_furniture_admiral_id'), 'admiral_furniture', ['admiral_id'], unique=False)
    op.create_index(op.f('ix_admiral_furniture_furniture_id'), 'admiral_furniture', ['furniture_id'], unique=False)
    op.create_table('admiral_quest', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('progress', sa.Integer(), nullable=True), sa.Column('state', sa.Integer(), nullable=True),
        sa.Column('data', sa.String(length=255), nullable=True), sa.Column('admiral_id', sa.Integer(), nullable=True),
        sa.Column('quest_id', sa.Integer(), nullable=True), sa.ForeignKeyConstraint(['admiral_id'], ['admiral.id'], ),
        sa.ForeignKeyConstraint(['quest_id'], ['quest.id'], ), sa.PrimaryKeyConstraint('id'))
    op.create_table('admiral_usables', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=True), sa.Column('admiral_id', sa.Integer(), nullable=True),
        sa.Column('usable_id', sa.Integer(), nullable=True), sa.ForeignKeyConstraint(['admiral_id'], ['admiral.id'], ),
        sa.ForeignKeyConstraint(['usable_id'], ['usable.id'], ), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_admiral_usables_admiral_id'), 'admiral_usables', ['admiral_id'], unique=False)
    op.create_index(op.f('ix_admiral_usables_usable_id'), 'admiral_usables', ['usable_id'], unique=False)
    op.create_table('fleet', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True), sa.Column('number', sa.Integer(), nullable=True),
        sa.Column('admiral_id', sa.Integer(), nullable=True), sa.ForeignKeyConstraint(['admiral_id'], ['admiral.id'], ),
        sa.PrimaryKeyConstraint('id'))
    op.create_table('quest_requirement', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('quest_id', sa.Integer(), nullable=True), sa.Column('required_quest_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['quest_id'], ['quest.id'], ),
        sa.ForeignKeyConstraint(['required_quest_id'], ['quest.id'], ), sa.PrimaryKeyConstraint('id'))
    op.create_table('ship', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('api_id', sa.Integer(), nullable=True), sa.Column('name', sa.String(), nullable=True),
        sa.Column('number', sa.Integer(), nullable=True), sa.Column('rarity', sa.Integer(), nullable=True),
        sa.Column('type_', sa.Integer(), nullable=True), sa.Column('voicef', sa.Integer(), nullable=True),
        sa.Column('slots', sa.Integer(), nullable=True), sa.Column('kai', sa.Boolean(), nullable=True),
        sa.Column('getmsg', sa.Text(), nullable=True), sa.Column('buildtime', sa.Integer(), nullable=True),
        sa.Column('maxslots', sa.Integer(), nullable=True), sa.Column('maxplanes', sa.String(), nullable=True),
        sa.Column('max_stats_id', sa.Integer(), nullable=True), sa.Column('base_stats_id', sa.Integer(), nullable=True),
        sa.Column('broken_resources_id', sa.Integer(), nullable=True),
        sa.Column('modern_resources_id', sa.Integer(), nullable=True),
        sa.Column('remodel_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['base_stats_id'], ['stats.id'], ),
        sa.ForeignKeyConstraint(['broken_resources_id'], ['resources.id'], ),
        sa.ForeignKeyConstraint(['max_stats_id'], ['stats.id'], ),
        sa.ForeignKeyConstraint(['modern_resources_id'], ['resources.id'], ),
        sa.ForeignKeyConstraint(['remodel_id'], ['remodel.id'], ), sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('remodel_id'))
    op.create_index(op.f('ix_ship_base_stats_id'), 'ship', ['base_stats_id'], unique=False)
    op.create_index(op.f('ix_ship_broken_resources_id'), 'ship', ['broken_resources_id'], unique=False)
    op.create_index(op.f('ix_ship_max_stats_id'), 'ship', ['max_stats_id'], unique=False)
    op.create_index(op.f('ix_ship_modern_resources_id'), 'ship', ['modern_resources_id'], unique=False)
    op.create_table('kanmusu', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('fleet_position', sa.Integer(), nullable=True), sa.Column('number', sa.Integer(), nullable=False),
        sa.Column('level', sa.Integer(), nullable=True), sa.Column('experience', sa.Integer(), nullable=True),
        sa.Column('current_hp', sa.Integer(), nullable=True), sa.Column('current_fuel', sa.Integer(), nullable=True),
        sa.Column('current_ammo', sa.Integer(), nullable=True), sa.Column('fatigue', sa.Integer(), nullable=True),
        sa.Column('locked', sa.Boolean(), nullable=True), sa.Column('active', sa.Boolean(), nullable=False),
        sa.Column('admiral_id', sa.Integer(), nullable=True), sa.Column('ship_id', sa.Integer(), nullable=True),
        sa.Column('fleet_id', sa.Integer(), nullable=True), sa.Column('stats_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['admiral_id'], ['admiral.id'], ),
        sa.ForeignKeyConstraint(['fleet_id'], ['fleet.id'], ), sa.ForeignKeyConstraint(['ship_id'], ['ship.id'], ),
        sa.ForeignKeyConstraint(['stats_id'], ['stats.id'], ), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_kanmusu_stats_id'), 'kanmusu', ['stats_id'], unique=False)
    op.create_table('quest_bonus', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('type_', sa.Integer(), nullable=True), sa.Column('quantity', sa.Integer(), nullable=True),
        sa.Column('quest_id', sa.Integer(), nullable=True), sa.Column('item_id', sa.Integer(), nullable=True),
        sa.Column('ship_id', sa.Integer(), nullable=True), sa.ForeignKeyConstraint(['item_id'], ['equipment.id'], ),
        sa.ForeignKeyConstraint(['quest_id'], ['quest.id'], ), sa.ForeignKeyConstraint(['ship_id'], ['ship.id'], ),
        sa.PrimaryKeyConstraint('id'))
    op.create_table('recipe', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('chance', sa.Integer(), nullable=True), sa.Column('ship_id', sa.Integer(), nullable=True),
        sa.Column('min_resources_id', sa.Integer(), nullable=True),
        sa.Column('max_resources_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['max_resources_id'], ['resources.id'], ),
        sa.ForeignKeyConstraint(['min_resources_id'], ['resources.id'], ),
        sa.ForeignKeyConstraint(['ship_id'], ['ship.id'], ), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_recipe_max_resources_id'), 'recipe', ['max_resources_id'], unique=False)
    op.create_index(op.f('ix_recipe_min_resources_id'), 'recipe', ['min_resources_id'], unique=False)
    op.create_table('dock', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('number', sa.Integer(), nullable=True), sa.Column('type_', sa.Integer(), nullable=True),
        sa.Column('state', sa.Integer(), nullable=True), sa.Column('complete', sa.BigInteger(), nullable=True),
        sa.Column('admiral_id', sa.Integer(), nullable=True), sa.Column('kanmusu_id', sa.Integer(), nullable=True),
        sa.Column('resources_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['admiral_id'], ['admiral.id'], ),
        sa.ForeignKeyConstraint(['kanmusu_id'], ['kanmusu.id'], ),
        sa.ForeignKeyConstraint(['resources_id'], ['resources.id'], ), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_dock_resources_id'), 'dock', ['resources_id'], unique=False)
    op.create_table('kanmusu_equipment', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('slot', sa.Integer(), nullable=True), sa.Column('kanmusu_id', sa.Integer(), nullable=True),
        sa.Column('admiral_equipment_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['admiral_equipment_id'], ['admiral_equipment.id'], ),
        sa.ForeignKeyConstraint(['kanmusu_id'], ['kanmusu.id'], ), sa.PrimaryKeyConstraint('id'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kanmusu_equipment')
    op.drop_index(op.f('ix_dock_resources_id'), table_name='dock')
    op.drop_table('dock')
    op.drop_index(op.f('ix_recipe_min_resources_id'), table_name='recipe')
    op.drop_index(op.f('ix_recipe_max_resources_id'), table_name='recipe')
    op.drop_table('recipe')
    op.drop_table('quest_bonus')
    op.drop_index(op.f('ix_kanmusu_stats_id'), table_name='kanmusu')
    op.drop_table('kanmusu')
    op.drop_index(op.f('ix_ship_modern_resources_id'), table_name='ship')
    op.drop_index(op.f('ix_ship_max_stats_id'), table_name='ship')
    op.drop_index(op.f('ix_ship_broken_resources_id'), table_name='ship')
    op.drop_index(op.f('ix_ship_base_stats_id'), table_name='ship')
    op.drop_table('ship')
    op.drop_table('quest_requirement')
    op.drop_table('fleet')
    op.drop_index(op.f('ix_admiral_usables_usable_id'), table_name='admiral_usables')
    op.drop_index(op.f('ix_admiral_usables_admiral_id'), table_name='admiral_usables')
    op.drop_table('admiral_usables')
    op.drop_table('admiral_quest')
    op.drop_index(op.f('ix_admiral_furniture_furniture_id'), table_name='admiral_furniture')
    op.drop_index(op.f('ix_admiral_furniture_admiral_id'), table_name='admiral_furniture')
    op.drop_table('admiral_furniture')
    op.drop_table('admiral_equipment')
    op.drop_table('role__user')
    op.drop_index(op.f('ix_remodel_id_resources'), table_name='remodel')
    op.drop_table('remodel')
    op.drop_table('quest')
    op.drop_index(op.f('ix_equipment_stats_id'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_resources_id'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_table('admiral')
    op.drop_table('user')
    op.drop_table('usable')
    op.drop_table('stats')
    op.drop_table('role')
    op.drop_table('resources')
    op.drop_table('furniture')
    ### end Alembic commands ###
