"""Un-versioned Admiral

Revision ID: f4ac668212c
Revises: 1f1490ca957f
Create Date: 2014-08-02 13:03:58.238161

"""

# revision identifiers, used by Alembic.
revision = 'f4ac668212c'
down_revision = '1f1490ca957f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admiral_version')
    op.drop_table('transaction')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('issued_at', sa.DATETIME(), nullable=True),
        sa.Column('remote_addr', sa.VARCHAR(length=50), nullable=True),
        sa.Column('user_id', sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], [u'user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admiral_version',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('user_id', sa.INTEGER(), nullable=True),
        sa.Column('nickname', sa.VARCHAR(length=255), nullable=True),
        sa.Column('last_login', sa.DATETIME(), nullable=True),
        sa.Column('level', sa.INTEGER(), nullable=True),
        sa.Column('rank', sa.INTEGER(), nullable=True),
        sa.Column('experience', sa.INTEGER(), nullable=True),
        sa.Column('tutorial_progress', sa.INTEGER(), nullable=True),
        sa.Column('furniture', sa.VARCHAR(length=100), nullable=True),
        sa.Column('furniture_coins', sa.INTEGER(), nullable=True),
        sa.Column('max_ships', sa.INTEGER(), nullable=True),
        sa.Column('max_equips', sa.INTEGER(), nullable=True),
        sa.Column('max_furniture', sa.INTEGER(), nullable=True),
        sa.Column('available_fleets', sa.INTEGER(), nullable=True),
        sa.Column('available_cdocks', sa.INTEGER(), nullable=True),
        sa.Column('available_rdocks', sa.INTEGER(), nullable=True),
        sa.Column('sortie_successes', sa.INTEGER(), nullable=True),
        sa.Column('sortie_total', sa.INTEGER(), nullable=True),
        sa.Column('expedition_successes', sa.INTEGER(), nullable=True),
        sa.Column('expedition_total', sa.INTEGER(), nullable=True),
        sa.Column('pvp_successes', sa.INTEGER(), nullable=True),
        sa.Column('pvp_total', sa.INTEGER(), nullable=True),
        sa.Column('transaction_id', sa.INTEGER(), nullable=False),
        sa.Column('end_transaction_id', sa.INTEGER(), nullable=True),
        sa.Column('operation_type', sa.SMALLINT(), nullable=False),
        sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    ### end Alembic commands ###
