"""Created User and Role tables

Revision ID: 386de93b0678
Revises: None
Create Date: 2014-08-01 22:17:16.087427

"""

# revision identifiers, used by Alembic.
revision = '386de93b0678'
down_revision = None

from alembic import op
import sqlalchemy as sa
import sqlalchemy.sql as ss

import datetime


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=80), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_table('user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('password', sa.String(length=255), nullable=False),
        sa.Column('confirmed_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
    )
    op.create_table('role__user',
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('role_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['role_id'], ['role.id']),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'])
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role__user')
    op.drop_table('user')
    op.drop_table('role')
    ### end Alembic commands ###
