"""Created User and Role tables

Revision ID: 386de93b0678
Revises: None
Create Date: 2014-08-01 22:17:16.087427

"""

# revision identifiers, used by Alembic.
revision = '386de93b0678'
down_revision = None

from alembic import op
import sqlalchemy as sa
import sqlalchemy.sql as ss

import datetime


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=80), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_table('user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('password', sa.String(length=255), nullable=False),
        sa.Column('confirmed_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
    )
    op.create_table('role__user',
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('role_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['role_id'], ['role.id']),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'])
    )
    ### end Alembic commands ###
    
    # --> Fixtures!
    role_table = ss.table('role',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=80), nullable=False),
        sa.Column('description', sa.Text(), nullable=True)
    )
    op.bulk_insert(role_table, [
        {
            'id': 1,
            'name': 'admin',
            'description': "Allowed to perform administrative tasks"
        },
        {
            'id': 2,
            'name': 'staff',
            'description': "Allowed to access staff-only information"
        },
        {
            'id': 3,
            'name': 'mod',
            'description': "Allowed to edit other users' information"
        }
    ])
    
    user_table = ss.table('user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('password', sa.String(length=255), nullable=False),
        sa.Column('confirmed_at', sa.DateTime(), nullable=True)
    )
    
    op.bulk_insert(user_table, [
        {
            'id': 1,
            'active': True,
            'email': 'admin@localhost',
            'password': 'password',
            'confirmed_at': datetime.datetime.now()
        }
    ])
    
    role__user_table = ss.table('role__user',
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('role_id', sa.Integer(), nullable=True)
    )
    op.bulk_insert(role__user_table, [
        { 'user_id': 1, 'role_id': 1 },
        { 'user_id': 1, 'role_id': 2 },
        { 'user_id': 1, 'role_id': 3 }
    ])


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role__user')
    op.drop_table('user')
    op.drop_table('role')
    ### end Alembic commands ###
