"""Add Recipe class.

Revision ID: 2096dc4473f
Revises: 400372d482a
Create Date: 2015-05-13 06:32:03.462570

"""

# revision identifiers, used by Alembic.
revision = '2096dc4473f'
down_revision = '400372d482a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ship_id', sa.Integer(), nullable=True),
    sa.Column('chance', sa.Integer(), nullable=True),
    sa.Column('minfuel', sa.Integer(), nullable=False),
    sa.Column('maxfuel', sa.Integer(), nullable=False),
    sa.Column('minammo', sa.Integer(), nullable=False),
    sa.Column('maxammo', sa.Integer(), nullable=False),
    sa.Column('minsteel', sa.Integer(), nullable=False),
    sa.Column('maxsteel', sa.Integer(), nullable=False),
    sa.Column('minbaux', sa.Integer(), nullable=False),
    sa.Column('maxbaux', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ship_id'], ['ship.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'dock', 'ship', ['ship_id'], ['id'])
    op.drop_column('dock', 'ship')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dock', sa.Column('ship', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'dock', type_='foreignkey')
    op.drop_table('recipe')
    ### end Alembic commands ###
