"""Add heartlock flag

Revision ID: 2f5f6f2eb17
Revises: 4cae4866bc8
Create Date: 2015-05-05 17:30:43.605134

"""

# revision identifiers, used by Alembic.
revision = '2f5f6f2eb17'
down_revision = '4cae4866bc8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admiral_ship', sa.Column('heartlocked', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admiral_ship', 'heartlocked')
    ### end Alembic commands ###
