"""Merge all DB revisions

Revision ID: 2f8220972dc
Revises: None
Create Date: 2015-05-06 16:16:35.692843

"""

# revision identifiers, used by Alembic.
revision = '2f8220972dc'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('afterlv', sa.Integer(), nullable=True),
    sa.Column('aftershipid', sa.Integer(), nullable=True),
    sa.Column('remodel_cost', sa.String(), nullable=True),
    sa.Column('rarity', sa.Integer(), nullable=True),
    sa.Column('broken', sa.String(), nullable=True),
    sa.Column('ammo_max', sa.Integer(), nullable=True),
    sa.Column('fuel_max', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('stype', sa.Integer(), nullable=True),
    sa.Column('voicef', sa.Integer(), nullable=True),
    sa.Column('modern_use', sa.String(), nullable=True),
    sa.Column('luck_base', sa.Integer(), nullable=True),
    sa.Column('firepower_base', sa.Integer(), nullable=True),
    sa.Column('torpedo_base', sa.Integer(), nullable=True),
    sa.Column('armour_base', sa.Integer(), nullable=True),
    sa.Column('antiair_base', sa.Integer(), nullable=True),
    sa.Column('antisub_base', sa.Integer(), nullable=True),
    sa.Column('los_base', sa.Integer(), nullable=True),
    sa.Column('evasion_base', sa.Integer(), nullable=True),
    sa.Column('luck_max', sa.Integer(), nullable=True),
    sa.Column('firepower_max', sa.Integer(), nullable=True),
    sa.Column('torpedo_max', sa.Integer(), nullable=True),
    sa.Column('armour_max', sa.Integer(), nullable=True),
    sa.Column('antiair_max', sa.Integer(), nullable=True),
    sa.Column('antisub_max', sa.Integer(), nullable=True),
    sa.Column('maxslots', sa.Integer(), nullable=True),
    sa.Column('maxlos', sa.Integer(), nullable=True),
    sa.Column('evasion_max', sa.Integer(), nullable=True),
    sa.Column('maxhp', sa.Integer(), nullable=True),
    sa.Column('srange', sa.Integer(), nullable=True),
    sa.Column('getmsg', sa.String(length=255), nullable=True),
    sa.Column('buildtime', sa.Integer(), nullable=True),
    sa.Column('maxplanes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('nickname', sa.String(length=255), nullable=False),
    sa.Column('api_token', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_token'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nickname')
    )
    op.create_table('admiral',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('tutorial_progress', sa.Integer(), nullable=True),
    sa.Column('furniture', sa.String(), nullable=True),
    sa.Column('furniture_coins', sa.Integer(), nullable=True),
    sa.Column('max_ships', sa.Integer(), nullable=True),
    sa.Column('max_equips', sa.Integer(), nullable=True),
    sa.Column('max_furniture', sa.Integer(), nullable=True),
    sa.Column('available_fleets', sa.Integer(), nullable=True),
    sa.Column('available_cdocks', sa.Integer(), nullable=True),
    sa.Column('available_rdocks', sa.Integer(), nullable=True),
    sa.Column('sortie_successes', sa.Integer(), nullable=True),
    sa.Column('sortie_total', sa.Integer(), nullable=True),
    sa.Column('expedition_successes', sa.Integer(), nullable=True),
    sa.Column('expedition_total', sa.Integer(), nullable=True),
    sa.Column('pvp_successes', sa.Integer(), nullable=True),
    sa.Column('pvp_total', sa.Integer(), nullable=True),
    sa.Column('resources', sa.String(), nullable=True),
    sa.Column('setup', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role__user',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('dock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('ship', sa.Integer(), nullable=True),
    sa.Column('complete', sa.BigInteger(), nullable=True),
    sa.Column('fuel', sa.Integer(), nullable=True),
    sa.Column('ammo', sa.Integer(), nullable=True),
    sa.Column('steel', sa.Integer(), nullable=True),
    sa.Column('baux', sa.Integer(), nullable=True),
    sa.Column('cmats', sa.Integer(), nullable=True),
    sa.Column('ship_id', sa.Integer(), nullable=True),
    sa.Column('admiral_idea', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admiral_idea'], ['admiral.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fleet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('admiral_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admiral_id'], ['admiral.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admiral_ship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admiralid', sa.Integer(), nullable=True),
    sa.Column('ship_id', sa.Integer(), nullable=True),
    sa.Column('fleet_id', sa.Integer(), nullable=True),
    sa.Column('ammo', sa.Integer(), nullable=True),
    sa.Column('fuel', sa.Integer(), nullable=True),
    sa.Column('fatigue', sa.Integer(), nullable=True),
    sa.Column('exp', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('repair_base', sa.String(), nullable=True),
    sa.Column('current_hp', sa.Integer(), nullable=True),
    sa.Column('luck', sa.Integer(), nullable=True),
    sa.Column('luck_eq', sa.Integer(), nullable=True),
    sa.Column('firepower', sa.Integer(), nullable=True),
    sa.Column('firepower_eq', sa.Integer(), nullable=True),
    sa.Column('armour', sa.Integer(), nullable=True),
    sa.Column('torpedo', sa.Integer(), nullable=True),
    sa.Column('torpedo_eq', sa.Integer(), nullable=True),
    sa.Column('antiair', sa.Integer(), nullable=True),
    sa.Column('antiair_eq', sa.Integer(), nullable=True),
    sa.Column('antisub', sa.Integer(), nullable=True),
    sa.Column('evasion', sa.Integer(), nullable=True),
    sa.Column('heartlocked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['admiralid'], ['admiral.id'], ),
    sa.ForeignKeyConstraint(['fleet_id'], ['fleet.id'], ),
    sa.ForeignKeyConstraint(['ship_id'], ['ship.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admiral_ship')
    op.drop_table('fleet')
    op.drop_table('dock')
    op.drop_table('role__user')
    op.drop_table('admiral')
    op.drop_table('user')
    op.drop_table('ship')
    op.drop_table('role')
    ### end Alembic commands ###
