"""rename local fleet id

Revision ID: 34df5956445
Revises: 400372d482a
Create Date: 2015-05-09 11:12:08.584101

"""

# revision identifiers, used by Alembic.
revision = '34df5956445'
down_revision = '400372d482a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admiral_ship', sa.Column('local_fleet_num', sa.Integer(), nullable=True))
    op.drop_column('admiral_ship', 'local_fleet_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admiral_ship', sa.Column('local_fleet_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('admiral_ship', 'local_fleet_num')
    ### end Alembic commands ###
