"""empty message

Revision ID: 3750492d6c2
Revises: 56cdcbcb52a
Create Date: 2015-05-04 15:04:41.964345

"""

# revision identifiers, used by Alembic.
revision = '3750492d6c2'
down_revision = '56cdcbcb52a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admiral_ship', sa.Column('fleet_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admiral_ship', 'fleet_id')
    ### end Alembic commands ###
