"""shrug

Revision ID: 3aacd161842
Revises: 4a6e8ba896
Create Date: 2015-05-14 23:42:26.709680

"""

# revision identifiers, used by Alembic.
revision = '3aacd161842'
down_revision = '4a6e8ba896'

from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dock_ship_id_fkey', 'dock', type_='foreignkey')
    op.create_foreign_key(None, 'dock', 'admiral_ship', ['ship_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dock', type_='foreignkey')
    op.create_foreign_key('dock_ship_id_fkey', 'dock', 'ship', ['ship_id'], ['id'])
    ### end Alembic commands ###
