"""Add HP column. Sort of a major feature, don't believe I forgot it.

Revision ID: 479311658ee
Revises: 2f5f6f2eb17
Create Date: 2015-05-05 17:49:28.133560

"""

# revision identifiers, used by Alembic.
revision = '47f9f6fa3a8'
down_revision = '2f5f6f2eb17'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admiral_ship', sa.Column('current_hp', sa.Integer(), nullable=True))
    op.add_column('admiral_ship', sa.Column('evasion', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admiral_ship', 'current_hp')
    op.drop_column('admiral_ship', 'evasion')
    ### end Alembic commands ###
