"""Add one-way Fleet->Expedition relationship.

Revision ID: 47fcd113d1e3
Revises: ecf3973e1118
Create Date: 2016-01-23 11:17:58.920534

"""

# revision identifiers, used by Alembic.
revision = '47fcd113d1e3'
down_revision = 'ecf3973e1118'

from alembic import op
import sqlalchemy as sa


def upgrade():
### commands auto generated by Alembic - please adjust! ###
    op.add_column('fleet', sa.Column('expedition_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fleet', 'expedition', ['expedition_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fleet', type_='foreignkey')
    op.drop_column('fleet', 'expedition_id')
    ### end Alembic commands ###
