"""Add setup flag

Revision ID: 4cae4866bc8
Revises: 1ba40f8eb27
Create Date: 2015-05-05 15:24:12.832284

"""

# revision identifiers, used by Alembic.
revision = '4cae4866bc8'
down_revision = '1ba40f8eb27'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admiral', sa.Column('setup', sa.Boolean(), nullable=True))
    op.add_column('fleet', sa.Column('admiral_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fleet', 'admiral_id')
    op.drop_column('admiral', 'setup')
    ### end Alembic commands ###
