"""Change db relationships in Recipe

Revision ID: 62f3d26f34ea
Revises: f20f12964a98
Create Date: 2016-01-18 17:57:08.616682

"""

# revision identifiers, used by Alembic.
revision = '62f3d26f34ea'
down_revision = 'f20f12964a98'

from alembic import op
import sqlalchemy as sa


def upgrade():
### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('recipe_min_resources_id_fkey', 'recipe', type_='foreignkey')
    op.drop_constraint('recipe_max_resources_id_fkey', 'recipe', type_='foreignkey')
    op.create_foreign_key(None, 'recipe', 'recipe__resources', ['max_resources_id'], ['id'])
    op.create_foreign_key(None, 'recipe', 'recipe__resources', ['min_resources_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.create_foreign_key('recipe_max_resources_id_fkey', 'recipe', 'resources', ['max_resources_id'], ['id'])
    op.create_foreign_key('recipe_min_resources_id_fkey', 'recipe', 'resources', ['min_resources_id'], ['id'])
    ### end Alembic commands ###
