"""Add fleet table

Revision ID: 91f3003b98
Revises: 35b43c28a04
Create Date: 2015-05-05 14:34:12.629008

"""

# revision identifiers, used by Alembic.
revision = '91f3003b98'
down_revision = '35b43c28a04'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fleet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fleet')
    ### end Alembic commands ###
