"""empty message

Revision ID: b5e404d415
Revises: 3750492d6c2
Create Date: 2015-05-04 20:43:25.954528

"""

# revision identifiers, used by Alembic.
revision = 'b5e404d415'
down_revision = '3750492d6c2'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admiral_ship', 'firepower_max')
    op.drop_column('admiral_ship', 'antisub_max')
    op.drop_column('admiral_ship', 'antiair_max')
    op.drop_column('admiral_ship', 'luck_max')
    op.drop_column('admiral_ship', 'armour_max')
    op.add_column('ship', sa.Column('antiair_base', sa.Integer(), nullable=True))
    op.add_column('ship', sa.Column('antiair_max', sa.Integer(), nullable=True))
    op.add_column('ship', sa.Column('antisub_base', sa.Integer(), nullable=True))
    op.add_column('ship', sa.Column('antisub_max', sa.Integer(), nullable=True))
    op.add_column('ship', sa.Column('armour_base', sa.Integer(), nullable=True))
    op.add_column('ship', sa.Column('armour_max', sa.Integer(), nullable=True))
    op.add_column('ship', sa.Column('buildtime', sa.Integer(), nullable=True))
    op.add_column('ship', sa.Column('evasion_base', sa.Integer(), nullable=True))
    op.add_column('ship', sa.Column('evasion_max', sa.Integer(), nullable=True))
    op.add_column('ship', sa.Column('firepower_base', sa.Integer(), nullable=True))
    op.add_column('ship', sa.Column('firepower_max', sa.Integer(), nullable=True))
    op.add_column('ship', sa.Column('getmsg', sa.String(length=255), nullable=True))
    op.add_column('ship', sa.Column('los_base', sa.Integer(), nullable=True))
    op.add_column('ship', sa.Column('luck_base', sa.Integer(), nullable=True))
    op.add_column('ship', sa.Column('luck_max', sa.Integer(), nullable=True))
    op.add_column('ship', sa.Column('maxlos', sa.Integer(), nullable=True))
    op.add_column('ship', sa.Column('maxplanes', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('ship', sa.Column('remodel_cost', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('ship', sa.Column('srange', sa.Integer(), nullable=True))
    op.drop_column('ship', 'ammo_use_base')
    op.drop_column('ship', 'fuel_use_base')
    op.create_unique_constraint(None, 'user', ['api_token'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user')
    op.add_column('ship', sa.Column('fuel_use_base', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ship', sa.Column('ammo_use_base', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('ship', 'srange')
    op.drop_column('ship', 'remodel_cost')
    op.drop_column('ship', 'maxplanes')
    op.drop_column('ship', 'maxlos')
    op.drop_column('ship', 'luck_max')
    op.drop_column('ship', 'luck_base')
    op.drop_column('ship', 'los_base')
    op.drop_column('ship', 'getmsg')
    op.drop_column('ship', 'firepower_max')
    op.drop_column('ship', 'firepower_base')
    op.drop_column('ship', 'evasion_max')
    op.drop_column('ship', 'evasion_base')
    op.drop_column('ship', 'buildtime')
    op.drop_column('ship', 'armour_max')
    op.drop_column('ship', 'armour_base')
    op.drop_column('ship', 'antisub_max')
    op.drop_column('ship', 'antisub_base')
    op.drop_column('ship', 'antiair_max')
    op.drop_column('ship', 'antiair_base')
    op.add_column('admiral_ship', sa.Column('armour_max', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('admiral_ship', sa.Column('luck_max', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('admiral_ship', sa.Column('antiair_max', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('admiral_ship', sa.Column('antisub_max', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('admiral_ship', sa.Column('firepower_max', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
