"""Add resourced_used to Expedition

Revision ID: dd5a707fe947
Revises: 699e07f138d7
Create Date: 2016-01-25 18:03:26.740415

"""

# revision identifiers, used by Alembic.
revision = 'dd5a707fe947'
down_revision = '699e07f138d7'

from alembic import op
import sqlalchemy as sa


def upgrade():
### commands auto generated by Alembic - please adjust! ###
    op.add_column('expedition', sa.Column('resources_used_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'expedition', 'resources', ['resources_used_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expedition', type_='foreignkey')
    op.drop_column('expedition', 'resources_used_id')
    ### end Alembic commands ###
