"""Shove expedition related things into Fleet, some more.

Revision ID: df0fd0bd9bed
Revises: 47fcd113d1e3
Create Date: 2016-01-23 11:33:58.100904

"""

# revision identifiers, used by Alembic.
revision = 'df0fd0bd9bed'
down_revision = '47fcd113d1e3'

from alembic import op
import sqlalchemy as sa


def upgrade():
### commands auto generated by Alembic - please adjust! ###
    op.add_column('expedition', sa.Column('time_taken', sa.BigInteger(), nullable=True))
    op.add_column('fleet', sa.Column('expedition_completed', sa.BigInteger(), nullable=True))
    ### end Alembic commands ###


def downgrade():
### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fleet', 'expedition_completed')
    op.drop_column('expedition', 'time_taken')
    ### end Alembic commands ###
