"""Add lastaction field to db

Revision ID: e9e831ffd0
Revises: 3aacd161842
Create Date: 2015-07-19 08:49:44.042107

"""

# revision identifiers, used by Alembic.
revision = 'e9e831ffd0'
down_revision = '3aacd161842'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admiral', sa.Column('lastaction', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admiral', 'lastaction')
    ### end Alembic commands ###
