"""Add new RecipeResources table because it's easier on the adding recipes side tbh

Revision ID: f20f12964a98
Revises: 553b99378da
Create Date: 2016-01-18 17:46:53.848727

"""

# revision identifiers, used by Alembic.
revision = 'f20f12964a98'
down_revision = '553b99378da'

from alembic import op
import sqlalchemy as sa


def upgrade():
### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe__resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fuel', sa.Integer(), nullable=True),
    sa.Column('ammo', sa.Integer(), nullable=True),
    sa.Column('steel', sa.Integer(), nullable=True),
    sa.Column('baux', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe__resources')
    ### end Alembic commands ###
